wps: [fix] Compare all 'WPS_NONCE_LEN' bytes instead of just one
Cppcheck 1.67

$ cppcheck --template "{file}:{line}: {severity} ({id}): {message}" \
  --quiet --force ./src/

> wps/wps_registrar.c:2498: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2589: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2596: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2663: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2670: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2750: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.
> wps/wps_registrar.c:2757: error (invalidFunctionArgBool): Invalid memcmp() argument nr 3. A non-boolean value is required.

The data type of the third argument 'os_memcmp' expects is 'size_t'.
In these cases it was given a boolean expression that always evaluated
to 'true' and was hence interpreted by 'os_memcmp' as an integer '1'.
Therefore, instead of all nonce's bytes only one was actually compared.